apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  application.properties: |
    server.port=8080
    logging.level.root=info
    logging.config=/etc/poc/logging/logback.xml
    spring.profiles.active=batch
    spring.datasource.url=jdbc:postgresql://psqldb:5432/pocdb?sslmode=require
    spring.datasource.username=postgresadmin
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.datasource.hikari.maximum-pool-size=50
    spring.aop.proxy-target-class=true
    spring.batch.jdbc.initialize-schema=ALWAYS
    spring.batch.job.enabled=false
    spring.liquibase.default-schema=poc
    spring.jpa.properties.hibernate.jdbc.batch_size=50
    spring.codec.max-in-memory-size=1MB

    springdoc.swagger-ui.path=/swagger-ui.html
    management.endpoints.enabled-by-default=false
    management.endpoints.web.exposure.include[0]=prometheus
    management.endpoints.web.exposure.include[1]=metrics
    management.endpoints.web.exposure.include[2]=health
    management.endpoint.health.enabled=true
    management.endpoint.health.show-details=always
    management.endpoint.health.probes.enabled=true
    management.endpoint.metrics.enabled=true
    management.endpoint.prometheus.enabled=true
