apiVersion: v1
kind: Service
metadata:
  name: poc-springboot-app-service
  labels:
    app: poc-springboot-app-service
  annotations:
    prometheus.io/port: "http"
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: 5005
      targetPort: 5005
      protocol: TCP
      name: debug
    - port: 9991
      targetPort: 9991
      protocol: TCP
      name: jconsole
  selector:
    app: poc-springboot-app
