apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: processing-service-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  endpoints:
    - interval: 15s
      port: http
      path: /actuator/prometheus
      scrapeTimeout: 14s
  selector:
    matchLabels:
      app: poc-springboot-app-service
  namespaceSelector:
    matchNames:
      - korem